name: Run pytest
on: 
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flask
          pip install authlib
          pip install werkzeug

      - name: PyTest
        run: |
          python -m pytest backend/examples/sample-rp/tests --junit-xml results/pytest.xml
        continue-on-error: true

      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results (Python 3.11)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/**/*.xml
